@startuml

title RDCU pour redémarrer le jeu 

participant ":JeuDeDes" as JeuDeDes
participant "joueurs:\nMap<String, Joueur>" as joueurs



-> JeuDeDes: redemarrerJeu()

note right of JeuDeDes
    selon Contrôleur
    (JeuDeDés est 
    l'object racine)
end note

JeuDeDes -> joueurs: clear()

note right of joueurs
    selon expert
end note


hide footbox

@enduml